#############################################################################
# Makefile for building: metlhedd
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Apr 28 23:30:24 2020
# Project:  metlhedd.pro
# Template: app
# Command: /ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/bin/qmake -o Makefile metlhedd.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc
CXX           = arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++98 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/include/QtCore -I/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/include/QtNetwork -I/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/include/QtGui -I/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/include -I. -I.
LINK          = arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib
LIBS          = $(SUBLIBS)  -L/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib -lQtGui -L/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib -lQtNetwork -lQtCore -lm -ldl -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/linux.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-base.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/qws.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/qconfig.pri \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_config.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/exclusive_builds.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/release.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_post.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/static.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/warn_on.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/unix/thread.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/moc.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/resources.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/uic.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/yacc.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/lex.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/include_source_dir.prf \
		metlhedd.pro
QMAKE_TARGET  = metlhedd
DESTDIR       = 
TARGET        = metlhedd

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: metlhedd.pro  /ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/linux.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-base.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-unix.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/qws.conf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/qconfig.pri \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_functions.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_config.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/exclusive_builds.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_pre.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/release.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_post.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/static.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/warn_on.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/unix/thread.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/moc.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/resources.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/uic.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/yacc.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/lex.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/include_source_dir.prf \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtGui.prl \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtNetwork.prl \
		/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtCore.prl
	$(QMAKE) -o Makefile metlhedd.pro
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/unix.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/linux.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/gcc-base-unix.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-base.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/g++-unix.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/common/qws.conf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/qconfig.pri:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_functions.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt_config.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/exclusive_builds.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_pre.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/release.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/default_post.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/static.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/warn_on.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/qt.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/unix/thread.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/moc.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/resources.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/uic.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/yacc.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/lex.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/mkspecs/features/include_source_dir.prf:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtGui.prl:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtNetwork.prl:
/ad/eng/courses/ec/ec535/bbb/Qt-4.8.7-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile metlhedd.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/metlhedd1.0.0 || $(MKDIR) .tmp/metlhedd1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/metlhedd1.0.0/ && $(COPY_FILE) --parents metlhedd.h .tmp/metlhedd1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/metlhedd1.0.0/ && (cd `dirname .tmp/metlhedd1.0.0` && $(TAR) metlhedd1.0.0.tar metlhedd1.0.0 && $(COMPRESS) metlhedd1.0.0.tar) && $(MOVE) `dirname .tmp/metlhedd1.0.0`/metlhedd1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/metlhedd1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp metlhedd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

