######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 28 23:30:23 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += metlhedd.h
SOURCES += main.cpp
